### ISSUE TITLE
Submit your week1 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project-2017/deliverables#1]
Submit your week 1 report here (deadline Sunday 08th October 2017).

Publish the link to your public GDrive slides.

**Comment by fserracant** [comment]
Team 4: https://docs.google.com/presentation/d/1mD5l4rEX7TZOrjyQuJWAxhxAxBT59L5TnxT7bfd_cuc/edit#slide=id.p

**Comment by ArnauVallve94** [comment]
Team 1: https://docs.google.com/presentation/d/1h_IvTp3NS4zqJGy6e84arBL9gWQiixCtaAkf5CJDcN4/edit#slide=id.p

**Comment by Milpoder** [comment]
Team 5: https://docs.google.com/presentation/d/1JIPhKvq60Xh5cetyX1DHKlyoAeR_lPIfSdl2zJ5ZJss/edit?usp=sharing

**Comment by noamor87** [comment]
Team 2: 
https://docs.google.com/presentation/d/1SExvOPmotB7IBvZFj7s5PBbbvXLoFFzn-RZ2WXxCpJA/edit#slide=id.g25b08976f7_0_7

**Comment by Ivancaminal72** [comment]
Team8: https://docs.google.com/presentation/d/1g9BtkjMb-nABzPwdrHGifOHBg_Y4RwUmulAFUYNXuB0/edit?usp=sharing

**Comment by JuanFMontesinos** [comment]
Team 6:
https://drive.google.com/file/d/0B1VspyR-zsxNaU5tR2txdHlfTWM/view

**Comment by franroldans** [comment]
Team 7: https://docs.google.com/presentation/d/1aLE1ayB36myKKJkIRbiX-4UQ93oUqdfu1qz3YJBpTBA/edit#slide=id.g26e7ec5902_0_16

**Comment by rogermm14** [comment]
Team 3: https://docs.google.com/presentation/d/1rPOdN7Z1m6REeQNnFs7L9DDnJm-tF86bHOfqCTjVN8g/edit?usp=sharing

**Comment by franroldans** [comment]
Team 7: https://docs.google.com/presentation/d/1aLE1ayB36myKKJkIRbiX-4UQ93oUqdfu1qz3YJBpTBA/edit?usp=sharing

Sorry, we accidentally shared a link that needs permissions.
